---
- name: Create VM infrastructure in GCP with Terraform
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - debug: msg="{{ tfvars | lower }}"

    - name: Build terraform.tfvars 
      ansible.builtin.template:
        src: terraform/terraform.tfvars.j2
        dest: terraform/terraform.tfvars

    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: terraform/

    - name: Run Terraform plan
      command: terraform plan -out=tfplan -var-file terraform.tfvars
      args:
        chdir: terraform/
    
    - name: Apply Terraform changes
      command: terraform apply -auto-approve -input=false tfplan 
      args:
        chdir: terraform/

    - name: Get instance ip from terraform output
      ansible.builtin.command: terraform output -raw instance_ip_address
      args:
        chdir: terraform/
      register: instance_ip_address

    - name: Add instance to inventory
      ansible.builtin.add_host:
        name: "{{ instance_ip_address.stdout }}"
        groups: nodes

- name: Wait for instance to become ready
  hosts: nodes
  gather_facts: false
  vars:
    ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

  tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300

- name: Configure instance with ansible
  hosts: nodes
  vars:
    ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

  roles:
    - RnodeC.beranode

- name: Destroy VM infrastructure in GCP with Terraform
  hosts: localhost
  connection: local
  gather_facts: false
  tags: ['never', 'down']

  tasks:
    - name: Terraform Destroy
      command: terraform destroy -auto-approve
      args:
        chdir: terraform/
